snapshot 2026-03-26T01:22:54.893499+00:00

diff --git a/docs/api/Makefile.am b/docs/api/Makefile.am
--- a/docs/api/Makefile.am
+++ b/docs/api/Makefile.am
@@ -27,27 +27,29 @@ SGML_CHAPTERS_SRC_DIR=$(srcdir)/src/chapters
 
 
 EXTRA_DIST = \
-	$(srcdir)/src \
-	$(srcdir)/images \
-	$(srcdir)/style.css \
+	$(builddir)/src \
+	$(builddir)/images \
+	$(builddir)/*.css \
+	$(builddir)/*.html  \
+	$(builddir)/*.png \
 	$(NULL)
 
 SOURCE_FILES_TO_COPY = \
 	$(srcdir)/src \
 	$(srcdir)/images \
-	$(srcdir)/style.css \
+	$(srcdir)/*.css \
 	$(srcdir)/*.html \
 	$(srcdir)/*.png \
 	$(NULL)
 
 CRYPTO_LIBS_LIST = \
-        openssl \
-        nss \
-        gnutls \
-        gcrypt \
-        mscrypto \
-        mscng \
-        $(NULL)
+	openssl \
+	nss \
+	gnutls \
+	mscng \
+	mscrypto \
+	gcrypt \
+	$(NULL)
 
 #
 # We need to pre-process original source files
@@ -64,49 +66,51 @@ EXAMPLES_SOURCE_FILES=\
 	$(shell find $(EXAMPLES_SOURCE_DIR) -name '*.c' -print) \
 	$(shell find $(EXAMPLES_SOURCE_DIR) -name '*.xml' -print)
 
-#
-# This script removes gtkdoc crap from final html
-#
-REMOVE_GTKDOCLINK=$(top_srcdir)/scripts/remove-gtkdoclink.pl
-
-all:
+all: docs-copy
 	@echo "======= Run 'make docs' in the xmlsec/docs folder to rebuild docs"
 
 # if build API docs, then we also have xsltproc
 if BUILD_API_DOCS
-docs: html-cleanup copy-images
+docs: html-cleanup
 
 else
 
-docs:
+docs: docs-copy
+	@echo "ERROR: To build API docs, make sure all necessary tools are installed"
+
+endif
+
+docs-copy:
 	@( \
-		echo "-- Copying api-docs..."; \
-		if [ z"$(srcdir)" != z"$(builddir)" -a z"`uname`" != z"Darwin" ]; \
+		echo "-- Copying api docs..."; \
+		if [ z"$(srcdir)" != z"$(builddir)" ]; \
 		then \
-		    $(CP) -ru $(SOURCE_FILES_TO_COPY) $(builddir)/ ; \
+			(chmod -Rf u+w $(EXTRA_DIST)  2>/dev/null || true) ; \
+			$(CP) -r $(SOURCE_FILES_TO_COPY) $(builddir)/ ; \
 		fi \
 	)
-endif
 
 html-cleanup: html
 	@( echo "-- Cleaning up result files"; \
-	   $(PERL) $(REMOVE_GTKDOCLINK) `find . -name "*.html" -print` \
+	   for f in `find . -name "*.html" -print` ; do \
+	       echo "-- Processing $$f..."; \
+	       $(SED) -i 's/<GTKDOCLINK[^>]*>/<font>/gI; s/<\/GTKDOCLINK[^>]*>/<\/font>/gI' "$$f" ; \
+	   done \
 	)
 
-# need to cleanup "bad" chars
-html: sgml $(MAIN_SGML_FILE) $(SGML_CHAPTERS_DIR) xmlsec-index
+html: docs-copy sgml $(MAIN_SGML_FILE) $(SGML_CHAPTERS_DIR) xmlsec-index
 	@$(GTKDOC_MKHTML) xmlsec $(MAIN_SGML_FILE)
 
 $(SGML_CHAPTERS_DIR): $(SGML_CHAPTERS_SRC_DIR) $(SGML_CHAPTERS_DIR)/.sentinel
 	@( \
 		echo "-- Copying chaptres..." ; \
-		$(CP) -ru $(SGML_CHAPTERS_SRC_DIR)/* $(SGML_CHAPTERS_DIR) \
+		$(CP) -r $(SGML_CHAPTERS_SRC_DIR)/* $(SGML_CHAPTERS_DIR) \
 	)
 
 $(MAIN_SGML_FILE): $(MAIN_SGML_SRC_FILE)
 	@( \
 		echo "-- Copying main sgml file..."; \
-		$(CP) -u $(MAIN_SGML_SRC_FILE) $(MAIN_SGML_FILE) \
+		$(CP) $(MAIN_SGML_SRC_FILE) $(MAIN_SGML_FILE) \
 	)
 #
 # Prepeare sgml files from sources for each library. We are also
@@ -120,46 +124,45 @@ sgml: sgml-base
 	@(for i in `find $(SGML_DIR) -name "*.sgml" -or -name "*.xml" -print` ; do \
 			echo "--- Fixing up '$$i'" ; \
 	        cat $$i | \
-	          sed 's!\(<dsig:\)\([^/]*\)\(\/>\)!\&lt;dsig:\2\/\&gt;!g' | \
-	          sed 's!\(<enc:\)\([^/]*\)\(\/>\)!\&lt;enc:\2\/\&gt;!g' | \
-	          sed 's!\(<dsig:\)\(\w*\)\(>\)!\&lt;dsig:\2\/\&gt;!g' | \
-	          sed 's!\(<enc:\)\(\w*\)\(>\)!\&lt;enc:\2\/\&gt;!g' | \
-	          sed 's!\(&lt;dsig:\)\([^/]*\)\(\/&gt;\)!<ulink URL=\"http://www.w3.org/TR/xmldsig-core/#sec-\2\">\1\2\3</ulink>!g' | \
-	          sed 's!\(&lt;enc:\)\([^/]*\)\(\/&gt;\)!<ulink URL=\"http://www.w3.org/TR/xmlenc-core/#sec-\2\">\1\2\3</ulink>!g' | \
-	          sed 's!<para \/>!<para></para>!g' | \
-	          sed 's!linkend=\"\(.*\)Ptr\"!linkend=\"\1\"!g' | \
-	          sed 's!<colspec [^/]*\/>!!g' | \
-	          sed 's!<programlisting language="C"!<programlisting!g' | \
-	          sed 's!\%gtkdocentities;!!g' | \
-	          $(PERL) -pe 's!title>\n!title>!g' | \
-	          $(PERL) -pe 's!title>\n!title>!g' | \
-	          $(PERL) -pe 's!<\/title><\/refsect1>\n!<\/title><para><\/para><\/refsect1>!g' | \
-	          $(PERL) -pe 's!para>\n!para>!g' > \
+	          $(SED) 's!\(<dsig:\)\([^/]*\)\(\/>\)!\&lt;dsig:\2\/\&gt;!g' | \
+	          $(SED) 's!\(<enc:\)\([^/]*\)\(\/>\)!\&lt;enc:\2\/\&gt;!g' | \
+	          $(SED) 's!\(<dsig:\)\(\w*\)\(>\)!\&lt;dsig:\2\/\&gt;!g' | \
+	          $(SED) 's!\(<enc:\)\(\w*\)\(>\)!\&lt;enc:\2\/\&gt;!g' | \
+	          $(SED) 's!\(&lt;dsig:\)\([^/]*\)\(\/&gt;\)!<ulink URL=\"http://www.w3.org/TR/xmldsig-core/#sec-\2\">\1\2\3</ulink>!g' | \
+	          $(SED) 's!\(&lt;enc:\)\([^/]*\)\(\/&gt;\)!<ulink URL=\"http://www.w3.org/TR/xmlenc-core/#sec-\2\">\1\2\3</ulink>!g' | \
+	          $(SED) 's!<para \/>!<para></para>!g' | \
+	          $(SED) 's!linkend=\"\(.*\)Ptr\"!linkend=\"\1\"!g' | \
+	          $(SED) 's!<colspec [^/]*\/>!!g' | \
+	          $(SED) 's!<programlisting language="C"!<programlisting!g' | \
+	          $(SED) 's!\%gtkdocentities;!!g' | \
+	          $(SED) 's!title>\n!title>!g' | \
+			  $(SED) 's!<\/title><\/refsect1>\n!<\/title><para><\/para><\/refsect1>!g' | \
+			  $(SED) 's!para>\n!para>!g' > \
 	          $$i.tmp; \
-	        mv -f $$i.tmp $$i; \
+	        $(MV) -f $$i.tmp $$i; \
 	 done);
 
 # gtkdoc-mkdb doesn't support --output-dir thus we have to "hack" it a litle bit
 sgml-base: scan $(SGML_DIR)/.sentinel
 	@( \
 	    echo "-- Create DocBook files for xmlsec-core" ; \
-	    rm -rf $(GTKDOC_MKDB_OUTPUT_DIR) $(SGML_DIR)/base ; \
+	    $(RM) -rf $(GTKDOC_MKDB_OUTPUT_DIR) $(SGML_DIR)/base ; \
 	    $(GTKDOC_MKDB) --module=xmlsec \
 		--xml-mode \
 		--main-sgml-file=$(SGML_DIR)/xmlsec-base.sgml \
 		--source-dir=$(SOURCE_CODE_DIR)/src/base \
 		--source-dir=$(SOURCE_CODE_DIR)/include/xmlsec/base ; \
-	    mv $(GTKDOC_MKDB_OUTPUT_DIR) $(SGML_DIR)/base ; \
+	    $(MV) $(GTKDOC_MKDB_OUTPUT_DIR) $(SGML_DIR)/base ; \
 	);
 	@(for i in $(CRYPTO_LIBS_LIST) ; do \
 	    echo "-- Create DocBook files for xmlsec-$$i" ; \
-	    rm -rf $(GTKDOC_MKDB_OUTPUT_DIR) $(SGML_DIR)/$$i ; \
+	    $(RM) -rf $(GTKDOC_MKDB_OUTPUT_DIR) $(SGML_DIR)/$$i ; \
 	    $(GTKDOC_MKDB) --module=xmlsec-$$i \
 		--xml-mode \
 		--main-sgml-file=$(SGML_DIR)/xmlsec-$$i.sgml \
 		--source-dir=$(SOURCE_CODE_DIR)/src/$$i \
 		--source-dir=$(SOURCE_CODE_DIR)/include/xmlsec/$$i ; \
-	    mv $(GTKDOC_MKDB_OUTPUT_DIR) $(SGML_DIR)/$$i ; \
+	    $(MV) $(GTKDOC_MKDB_OUTPUT_DIR) $(SGML_DIR)/$$i ; \
 	done);
 
 scan: SOURCE_CODEs example_sources
@@ -190,42 +193,42 @@ SOURCE_CODEs: $(SOURCE_CODE_FILES) $(SOURCE_CODE_DIR)/.sentinel SOURCE_CODEs_cle
 	@( \
 	for i in $(SOURCE_CODE_FILES) ; do \
 		folder_name=`echo "$$i" | \
-			sed 's#$(top_srcdir)/##' | \
-			sed 's#$(top_builddir)/##' | \
-			sed 's#/[^/]*$$##'`; \
+	        $(SED) 's#$(top_srcdir)/##' | \
+	        $(SED) 's#$(top_builddir)/##' | \
+	        $(SED) 's#/[^/]*$$##'`; \
 	    file_name=`echo "$$i" | \
-	    	sed 's#.*/##'`; \
+	        $(SED) 's#.*/##'`; \
 	    mkdir -p "$(SOURCE_CODE_DIR)/$$folder_name"; \
 	    cat "$$i" | \
-		    sed 's/#if.*//' | \
-		    sed 's/#el.*//' | \
-		    sed 's/#end.*//' | \
-		    sed 's/XMLSEC_CRYPTO_EXPORT//' | \
-		    sed 's/XMLSEC_EXPORT_VAR//' | \
-		    sed 's/XMLSEC_EXPORT//' | \
-		    sed 's/XMLSEC_ERRORS_PRINTF_ATTRIBUTE//' > \
-		    $(SOURCE_CODE_DIR)/$$folder_name/$$file_name; \
+	        $(SED) 's/#if.*//' | \
+	        $(SED) 's/#el.*//' | \
+	        $(SED) 's/#end.*//' | \
+	        $(SED) 's/XMLSEC_CRYPTO_EXPORT//' | \
+	        $(SED) 's/XMLSEC_EXPORT_VAR//' | \
+	        $(SED) 's/XMLSEC_EXPORT//' | \
+	        $(SED) 's/XMLSEC_ERRORS_PRINTF_ATTRIBUTE//' > \
+	        $(SOURCE_CODE_DIR)/$$folder_name/$$file_name; \
 	done);
-	@mv -f $(SOURCE_CODE_DIR)/src/*.c $(SOURCE_CODE_DIR)/src/base
-	@mv -f $(SOURCE_CODE_DIR)/include/xmlsec/*.h $(SOURCE_CODE_DIR)/include/xmlsec/base
-	@rm -f $(SOURCE_CODE_DIR)/include/xmlsec/*/symbols.h
+	@$(MV) -f $(SOURCE_CODE_DIR)/src/*.c $(SOURCE_CODE_DIR)/src/base
+	@$(MV) -f $(SOURCE_CODE_DIR)/include/xmlsec/*.h $(SOURCE_CODE_DIR)/include/xmlsec/base
+	@$(RM) -f $(SOURCE_CODE_DIR)/include/xmlsec/*/symbols.h
 	@echo "-- Remove macros documented in openssl module to avoid duplicate IDs"
-	@sed -i '/^#define XMLSEC_NO_MD5\b/d; /^#define XMLSEC_NO_EDDSA\b/d; /^#define XMLSEC_NO_HKDF\b/d' \
+	@$(SED) -i '/^#define XMLSEC_NO_MD5\b/d; /^#define XMLSEC_NO_EDDSA\b/d; /^#define XMLSEC_NO_HKDF\b/d' \
 	    $(SOURCE_CODE_DIR)/include/xmlsec/nss/crypto.h
 
 SOURCE_CODEs_cleanup: $(SOURCE_CODE_DIR)/.sentinel
-	@rm -rf $(SOURCE_CODE_DIR)/*
+	@$(RM) -rf $(SOURCE_CODE_DIR)/*
 
 #
 # Create index for all functions. For macros and defines need to add -CAPS suffix
 #
 xmlsec-index: scan $(SGML_DIR)/.sentinel
-	@grep -h '<NAME>.*</NAME>' $(SCAN_DIR)/xmlsec-*decl.txt | \
-		grep -v '<NAME>extern</NAME>' | \
-		sort -u | \
-		sed 's#_#-#g' | \
-		sed 's#<NAME>\([^-]*\)-\([^<]*\)</NAME>#<listitem><para><link linkend=\"\1-\2-CAPS\">\1-\2</link></para></listitem>#g' | \
-		sed 's#<NAME>\([^<]*\)</NAME>#<listitem><para><link linkend=\"\1\">\1</link></para></listitem>#g' > \
+	@$(GREP) -h '<NAME>.*</NAME>' $(SCAN_DIR)/xmlsec-*decl.txt | \
+		$(GREP) -v '<NAME>extern</NAME>' | \
+		$(SORT) -u | \
+		$(SED) 's#_#-#g' | \
+		$(SED) 's#<NAME>\([^-]*\)-\([^<]*\)</NAME>#<listitem><para><link linkend=\"\1-\2-CAPS\">\1-\2</link></para></listitem>#g' | \
+		$(SED) 's#<NAME>\([^<]*\)</NAME>#<listitem><para><link linkend=\"\1\">\1</link></para></listitem>#g' > \
 		$(SGML_DIR)/xmlsec-index.sgml
 
 #
@@ -236,31 +239,25 @@ xmlsec-index: scan $(SGML_DIR)/.sentinel
 #
 example_sources: $(EXAMPLES_DIR)/.sentinel
 	@echo "-- Preprocessing example source files into '$(EXAMPLES_DIR)' ..."
-	@rm -rf $(EXAMPLES_DIR)/*
+	@$(RM) -rf $(EXAMPLES_DIR)/*
 	@(for i in $(EXAMPLES_SOURCE_FILES) ; do \
-	    file_name=`echo $$i | sed 's#.*/##' | sed 's#\..*$$##'`; \
-	    file_ext=`echo $$i | sed 's#.*/##' | sed 's#.*\.##'`; \
+	    file_name=`echo $$i | $(SED) 's#.*/##' | $(SED) 's#\..*$$##'`; \
+	    file_ext=`echo $$i | $(SED) 's#.*/##' | $(SED) 's#.*\.##'`; \
 	    echo "--- Converting $$file_name.$$file_ext to $$file_name.sgml ..."; \
-	    file_title=`cat $$i | grep 'XML Security Library example: ' | sed 's#^.*: *##'`; \
+	    file_title=`cat $$i | $(GREP) 'XML Security Library example: ' | $(SED) 's#^.*: *##'`; \
 	    echo "<sect2 id=\"xmlsec-example-$$file_name\" >" > \
 	        $(EXAMPLES_DIR)/$$file_name.sgml; \
 	    echo "<title>$$file_name.$$file_ext</title><para><informalexample><programlisting>" >> \
 		    $(EXAMPLES_DIR)/$$file_name.sgml; \
 	    cat $$i | \
-		sed "s#&#\&amp;#g" | \
-		sed "s#<#\&lt;#g" | \
-		sed "s#>#\&gt;#g" >> \
+		$(SED) "s#&#\&amp;#g" | \
+		$(SED) "s#<#\&lt;#g" | \
+		$(SED) "s#>#\&gt;#g" >> \
 		    $(EXAMPLES_DIR)/$$file_name.sgml; \
 	    echo "</programlisting></informalexample></para></sect2>" >> \
 		    $(EXAMPLES_DIR)/$$file_name.sgml; \
 	done);
 
-copy-images:
-	@( if [ z"$(builddir)" != z"$(srcdir)" ] ; then \
-		echo "Copying images ..." ; \
-		mkdir -p $(builddir)/images ; \
-		cp $(srcdir)/images/*.png $(builddir)/images/ ; \
-	fi ; )
 
 # A single pattern rule will create all appropriate folders as required
 # otherwise make (annoyingly) deletes it
@@ -271,43 +268,35 @@ copy-images:
 	@touch $@
 
 dist-hook:
-	@( \
-		echo "-- Copying html..." ; \
-		$(CP) -p $(srcdir)/*.html $(srcdir)/*.png $(distdir)/ \
-	)
 	@(for i in `find $(distdir) -name ".sentinel" -print` ; do \
 		echo "Removing some files '$$i' before dist ... " ; \
-		rm $$i ; \
+		$(RM) $$i ; \
 	done )
 	@(for i in `find $(distdir) -name "*.sgml.bak" -print` ; do \
 		echo "Removing some files '$$i' before dist ... " ; \
-		rm "$$i" ; \
+		$(RM) "$$i" ; \
 	done ; )
 
 clean-local:
-	-rm -rf $(SOURCE_CODE_DIR) $(EXAMPLES_DIR) $(SCAN_DIR)/*.txt $(SGML_DIR) $(GTKDOC_MKDB_OUTPUT_DIR)
-	-rm -f *.stamp *.types index.sgml
-	@( if [ z"$(builddir)" != z"$(srcdir)" ] ; then \
-    	(chmod -R u+w $(builddir)/src || true) && rm -rf $(builddir)/src ; \
-    	(chmod -R u+w $(builddir)/images || true) && rm -rf $(builddir)/images ; \
-    	(chmod -R u+w $(builddir)/*.png || true) && rm -rf $(builddir)/*.png ; \
-	 fi ; )
+	@$(RM) -rf $(SOURCE_CODE_DIR) $(EXAMPLES_DIR) $(SCAN_DIR)/*.txt $(SGML_DIR) $(GTKDOC_MKDB_OUTPUT_DIR)
+	@$(RM) -f *.stamp *.types index.sgml
+	@( \
+		if [ z"$(builddir)" != z"$(srcdir)" ] ; \
+		then \
+			(chmod -Rf u+w $(builddir)/xmlsec.devhelp2 $(EXTRA_DIST) 2>/dev/null || true) ; \
+			$(RM) -rf $(builddir)/xmlsec.devhelp2 $(EXTRA_DIST) ; \
+	 	fi ; \
+	)
 
 distclean-local: clean-local
 
 install-data-local:
-	$(mkinstalldirs) $(DESTDIR)$(TARGET_DIR)
-	$(mkinstalldirs) $(DESTDIR)$(TARGET_DIR)/images
-	@( if [ -f "$(builddir)/index.html" ] ; then \
-		echo "Installing docs from build folder: '$(builddir)' ..." ; \
-		@INSTALL@ -m 0644 $(builddir)/*.html $(builddir)/*.png $(builddir)/*.css $(DESTDIR)$(TARGET_DIR) ; \
-		@INSTALL@ -m 0644 $(builddir)/images/*.png $(DESTDIR)$(TARGET_DIR)/images ; \
-	else  \
-		echo "Installing docs from source folder: '$(srcdir)' ..." ; \
-		@INSTALL@ -m 0644 $(srcdir)/*.html $(srcdir)/*.png $(srcdir)/*.css $(DESTDIR)$(TARGET_DIR) ; \
-		@INSTALL@ -m 0644 $(srcdir)/images/*.png $(DESTDIR)$(TARGET_DIR)/images ; \
-	fi ; )
+	@echo "Installing api docs ..."
+	@$(mkinstalldirs) $(DESTDIR)$(TARGET_DIR)
+	@$(mkinstalldirs) $(DESTDIR)$(TARGET_DIR)/images
+	@INSTALL@ -m 0644 $(builddir)/*.html $(builddir)/*.png $(builddir)/*.css $(DESTDIR)$(TARGET_DIR)
+	@INSTALL@ -m 0644 $(builddir)/images/*.png $(DESTDIR)$(TARGET_DIR)/images
 
 uninstall-local:
-	@rm -rf $(DESTDIR)$(TARGET_DIR)
+	@$(RM) -rf $(DESTDIR)$(TARGET_DIR)
 
